[package]
name = "taganrog"
version = "0.1.0"
edition = "2021"
publish = false
authors = [
    "Ivan Yaremenchuk <trooper982@gmail.com>"
]

[dependencies]
amplify = "4.5"
amplify_derive = "4.0"
anyhow = { version = "1.0", features = ["std"] }
async-trait = "0.1"
axum = { version = "0.7", features = ["multipart", "tower-log", "macros"] }
axum-macros = "0.4"
axum-template = { version = "2.1", features = ["minijinja"] }
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.4", features = ["derive", "env"] }
fastmurmur3 = "0.2"
futures = "0.3"
heapless = { version = "0.8", features = ["serde"] }
http-auth-basic = "0.3"
infer = { version = "0.15", default-features = false }
itertools = "0.12"
levenshtein = "1.0"
matches = { version = "0.1" }
minijinja = "1.0"
nanoid = "0.4"
path-absolutize = "3.1"
rand = "0.8"
reqwest = { version = "0.11", features = ["json"] }
relative-path = "1.9"
rmp-serde = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
surrealdb = { version = "1.1", features = ["kv-rocksdb"] }
time = "0.3"
thiserror = "1.0"
tokio = { version = "1.35", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["trace", "cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.7", features = ["serde", "v4", "fast-rng"] }
