[package]
name = "taganrog"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.4", features = ["multipart"] }
tokio = { version = "1.25.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "any", "postgres", "chrono"] }
serde = "1.0.152"
serde_json = "1.0.92"
chrono = { version = "0.4.23", features = ["serde"] }
rust-s3 = { version = "0.32.3", features = ["tokio-rustls-tls"] }
futures = "0.3.26"
fastmurmur3 = "0.1.2"
uuid = "1.2.2"
